# Orthodox Connect - Developed by dgm (dgm@tuta.com)
# orthodox-connect/jitsi/nginx.conf

server {
	listen 80;
	server_name _;

	location = /healthz {
		access_log off;
		add_header Content-Type text/plain;
		return 200 "ok\n";
	}

	location / {
		root /usr/share/nginx/html;
		index index.html;
		try_files $uri $uri/ /index.html;
	}
}
